name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php_version:
          - 8.0
          - 7.4
          - 7.3
          - 7.2
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@2.13.0
        with:
          php-version: ${{ matrix.php_version }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run unit test suite
        run: make phpunit

      - name: Run feature test suite
        run: make behat
